services:
  postgres:
    image: postgres:16
    container_name: payflow-postgres
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow
      POSTGRES_DB: payflow
    ports:
      - "5432:5432"
    volumes:
      - payflow-postgres-data:/var/lib/postgresql/data

volumes:
  payflow-postgres-data: